//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.PhoenixApp.Domain.MainBoundedContext.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.PhoenixApp.Domain.MainBoundedContext.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deposit money in locked account.
        /// </summary>
        internal static string exception_BankAccountCannotDeposit {
            get {
                return ResourceManager.GetString("exception_BankAccountCannotDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot withdraw in bankaccount, this is locked or amount is greather than balance.
        /// </summary>
        internal static string exception_BankAccountCannotWithdraw {
            get {
                return ResourceManager.GetString("exception_BankAccountCannotWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount for withdraw operation.
        /// </summary>
        internal static string exception_BankAccountInvalidWithdrawAmount {
            get {
                return ResourceManager.GetString("exception_BankAccountInvalidWithdrawAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot accept non requested friendship.
        /// </summary>
        internal static string exception_CannotAcceptNonRequestedFriendship {
            get {
                return ResourceManager.GetString("exception_CannotAcceptNonRequestedFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend1 is null or Friend1 is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullAcceptor {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullAcceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is null or Country is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullCountry {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null or Customer is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullCustomer {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend2 is null or Friend2 is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullInitiator {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullInitiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is null or Product is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullProduct {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel non requested friendship.
        /// </summary>
        internal static string exception_CannotCancelNonRequestedFriendship {
            get {
                return ResourceManager.GetString("exception_CannotCancelNonRequestedFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reject non requested friendship.
        /// </summary>
        internal static string exception_CannotRejectNonRequestedFriendship {
            get {
                return ResourceManager.GetString("exception_CannotRejectNonRequestedFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send friend request to the same user.
        /// </summary>
        internal static string exception_CannotSendFriendshipWhenInitiatorIsTheSameAsAcceptor {
            get {
                return ResourceManager.GetString("exception_CannotSendFriendshipWhenInitiatorIsTheSameAsAcceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transfer money to the same bank account.
        /// </summary>
        internal static string exception_CannotTransferMoneyWhenFromIsTheSameAsTo {
            get {
                return ResourceManager.GetString("exception_CannotTransferMoneyWhenFromIsTheSameAsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request already exists.
        /// </summary>
        internal static string exception_FriendRequestAlreadyExists {
            get {
                return ResourceManager.GetString("exception_FriendRequestAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendship acceptor cannot be null or empty.
        /// </summary>
        internal static string exception_FriendshipAcceptorCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("exception_FriendshipAcceptorCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship already exists.
        /// </summary>
        internal static string exception_FriendshipAlreadyExists {
            get {
                return ResourceManager.GetString("exception_FriendshipAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendship cannot be null or with empty id.
        /// </summary>
        internal static string exception_FriendshipCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("exception_FriendshipCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendship initiator cannot be null or empty.
        /// </summary>
        internal static string exception_FriendshipInitiatorCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("exception_FriendshipInitiatorCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data in order line, check the values, amount of items must be greater than zero.
        /// </summary>
        internal static string exception_InvalidDataForOrderLine {
            get {
                return ResourceManager.GetString("exception_InvalidDataForOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid friendship action.
        /// </summary>
        internal static string exception_InvalidFriendshipAction {
            get {
                return ResourceManager.GetString("exception_InvalidFriendshipAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order number pattern .
        /// </summary>
        internal static string exception_OrderNumberSpecificationInvalidOrderNumberPattern {
            get {
                return ResourceManager.GetString("exception_OrderNumberSpecificationInvalidOrderNumberPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendship request was not found.
        /// </summary>
        internal static string exception_ProfileFriendshipWasNotFound {
            get {
                return ResourceManager.GetString("exception_ProfileFriendshipWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit from account with identifier {0}.
        /// </summary>
        internal static string messages_TransactionFromMessage {
            get {
                return ResourceManager.GetString("messages_TransactionFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw to account with identifier {0}.
        /// </summary>
        internal static string messages_TransactionToMessage {
            get {
                return ResourceManager.GetString("messages_TransactionToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account number cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankAccountNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankAccountNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account check digits cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankCheckDigitsCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankCheckDigitsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account national bank code cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankNationalBankCodeCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankNationalBankCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account office number cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankOfficeNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankOfficeNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer id  in bank account cannot be empty.
        /// </summary>
        internal static string validation_BankAccountCustomerIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_BankAccountCustomerIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account number cannot be null.
        /// </summary>
        internal static string validation_BankAccountNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryISOCode cannot be null or empty string.
        /// </summary>
        internal static string validation_CountryCountryISOCodeCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CountryCountryISOCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName cannot be null or empty string.
        /// </summary>
        internal static string validation_CountryCountryNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CountryCountryNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryId is not associated for this Customer.
        /// </summary>
        internal static string validation_CustomerCountryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_CustomerCountryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstName property cannot be null or empty string.
        /// </summary>
        internal static string validation_CustomerFirstNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CustomerFirstNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName property cannot be null or empty string.
        /// </summary>
        internal static string validation_CustomerLastNameCannotBeBull {
            get {
                return ResourceManager.GetString("validation_CustomerLastNameCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address property cannot be null or empty string.
        /// </summary>
        internal static string validation_EmailAddressCannotBenull {
            get {
                return ResourceManager.GetString("validation_EmailAddressCannotBenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile id cannot be a empty identifier.
        /// </summary>
        internal static string validation_EmailProfileIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_EmailProfileIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendship initiator id and acceptor id cannot be the same.
        /// </summary>
        internal static string validation_FriendshipPartiesCannotBeSame {
            get {
                return ResourceManager.GetString("validation_FriendshipPartiesCannotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile id cannot be a empty identifier.
        /// </summary>
        internal static string validation_InstaceMessageProfileIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_InstaceMessageProfileIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IM Screen Name property cannot be null or empty string.
        /// </summary>
        internal static string validation_InstaceMessageScreenNameCannotBenull {
            get {
                return ResourceManager.GetString("validation_InstaceMessageScreenNameCannotBenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile Id of a media cannot be empty.
        /// </summary>
        internal static string validation_MediaProfileIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_MediaProfileIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Url cannot be empty.
        /// </summary>
        internal static string validation_MediaUrlCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_MediaUrlCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null or Customer is in Transient state.
        /// </summary>
        internal static string validation_OrderCustomerIdCannotBenull {
            get {
                return ResourceManager.GetString("validation_OrderCustomerIdCannotBenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amount property cannot be less than 1.
        /// </summary>
        internal static string validation_OrderLineAmountLessThanOne {
            get {
                return ResourceManager.GetString("validation_OrderLineAmountLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Discount cannot be less than 0 or greater than 1.
        /// </summary>
        internal static string validation_OrderLineDiscountCannotBeLessThanZeroOrGreaterThanOne {
            get {
                return ResourceManager.GetString("validation_OrderLineDiscountCannotBeLessThanZeroOrGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderLine cannot have associated order.
        /// </summary>
        internal static string validation_OrderLineOrderIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_OrderLineOrderIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product id cannot be a empty identifier.
        /// </summary>
        internal static string validation_OrderLineProductIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_OrderLineProductIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice cannot be less than zero.
        /// </summary>
        internal static string validation_OrderLineUnitPriceLessThanZero {
            get {
                return ResourceManager.GetString("validation_OrderLineUnitPriceLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number property cannot be null or empty string.
        /// </summary>
        internal static string validation_PhoneNumberCannotBenull {
            get {
                return ResourceManager.GetString("validation_PhoneNumberCannotBenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile id cannot be a empty identifier.
        /// </summary>
        internal static string validation_PhoneProfileIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_PhoneProfileIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of a post cannot be null or empty.
        /// </summary>
        internal static string validation_PostContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_PostContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile Id of a post cannot be empty.
        /// </summary>
        internal static string validation_PostProfileIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_PostProfileIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of a post cannot be null or empty.
        /// </summary>
        internal static string validation_PostTitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_PostTitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in stock cannot be less than zero.
        /// </summary>
        internal static string validation_ProductAmountLessThanZero {
            get {
                return ResourceManager.GetString("validation_ProductAmountLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be null or empty.
        /// </summary>
        internal static string validation_ProductDescriptionCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductDescriptionCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be null or empty.
        /// </summary>
        internal static string validation_ProductTitleCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductTitleCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice in stock cannot be less than zero.
        /// </summary>
        internal static string validation_ProductUnitPriceLessThanZero {
            get {
                return ResourceManager.GetString("validation_ProductUnitPriceLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile birthday cannot be less than 18 years old.
        /// </summary>
        internal static string validation_ProfileBirthdayCannotBeLessThan18 {
            get {
                return ResourceManager.GetString("validation_ProfileBirthdayCannotBeLessThan18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile birthday is invalid.
        /// </summary>
        internal static string validation_ProfileBirthdayInvalid {
            get {
                return ResourceManager.GetString("validation_ProfileBirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile email cannot be a empty.
        /// </summary>
        internal static string validation_ProfileEmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileEmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstName property cannot be null or empty string.
        /// </summary>
        internal static string validation_ProfileFirstNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ProfileFirstNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName property cannot be null or empty string.
        /// </summary>
        internal static string validation_ProfileLastNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ProfileLastNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile sex cannot be unknown.
        /// </summary>
        internal static string validation_ProfileSexCannotBeUnknown {
            get {
                return ResourceManager.GetString("validation_ProfileSexCannotBeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile username cannot be a empty identifier.
        /// </summary>
        internal static string validation_ProfileUserNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileUserNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile viewer cannot be same as viewed.
        /// </summary>
        internal static string validation_ProfileViewerCannotBeSame {
            get {
                return ResourceManager.GetString("validation_ProfileViewerCannotBeSame", resourceCulture);
            }
        }
    }
}
