// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Phoenix.PhoenixApp.Presentation.MVC.Client.Controllers
{
    public partial class EditController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EditController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult About()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.About);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Achievements()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Achievements);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteConfirmed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Living()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Living);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ProfileSummary()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileSummary);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Results()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Results);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Resume()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Resume);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EditController Actions { get { return MVCT.Edit; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Edit";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Edit";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string About = "About";
            public readonly string Achievements = "Achievements";
            public readonly string BasicInfo = "BasicInfo";
            public readonly string Contact = "Contact";
            public readonly string Delete = "Delete";
            public readonly string DeleteConfirmed = "Delete";
            public readonly string Index = "Index";
            public readonly string Living = "Living";
            public readonly string Picture = "Picture";
            public readonly string ProfileSummary = "ProfileSummary";
            public readonly string Results = "Results";
            public readonly string Resume = "Resume";
            public readonly string Sport = "Sport";
            public readonly string WorkEdu = "WorkEdu";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string About = "About";
            public const string Achievements = "Achievements";
            public const string BasicInfo = "BasicInfo";
            public const string Contact = "Contact";
            public const string Delete = "Delete";
            public const string DeleteConfirmed = "Delete";
            public const string Index = "Index";
            public const string Living = "Living";
            public const string Picture = "Picture";
            public const string ProfileSummary = "ProfileSummary";
            public const string Results = "Results";
            public const string Resume = "Resume";
            public const string Sport = "Sport";
            public const string WorkEdu = "WorkEdu";
        }


        static readonly ActionParamsClass_About s_params_About = new ActionParamsClass_About();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_About AboutParams { get { return s_params_About; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_About
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Achievements s_params_Achievements = new ActionParamsClass_Achievements();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Achievements AchievementsParams { get { return s_params_Achievements; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Achievements
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_BasicInfo s_params_BasicInfo = new ActionParamsClass_BasicInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BasicInfo BasicInfoParams { get { return s_params_BasicInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BasicInfo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Contact s_params_Contact = new ActionParamsClass_Contact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Contact ContactParams { get { return s_params_Contact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Contact
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteConfirmed s_params_DeleteConfirmed = new ActionParamsClass_DeleteConfirmed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteConfirmed DeleteConfirmedParams { get { return s_params_DeleteConfirmed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteConfirmed
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Living s_params_Living = new ActionParamsClass_Living();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Living LivingParams { get { return s_params_Living; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Living
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ProfileSummary s_params_ProfileSummary = new ActionParamsClass_ProfileSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProfileSummary ProfileSummaryParams { get { return s_params_ProfileSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProfileSummary
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Results s_params_Results = new ActionParamsClass_Results();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Results ResultsParams { get { return s_params_Results; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Results
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Resume s_params_Resume = new ActionParamsClass_Resume();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Resume ResumeParams { get { return s_params_Resume; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Resume
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Sport s_params_Sport = new ActionParamsClass_Sport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Sport SportParams { get { return s_params_Sport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Sport
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_WorkEdu s_params_WorkEdu = new ActionParamsClass_WorkEdu();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WorkEdu WorkEduParams { get { return s_params_WorkEdu; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WorkEdu
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _BasicInfo = "_BasicInfo";
                public readonly string _Contact = "_Contact";
                public readonly string _Living = "_Living";
                public readonly string _Sport = "_Sport";
                public readonly string _WorkEdu = "_WorkEdu";
                public readonly string BasicInfo = "BasicInfo";
                public readonly string Contact = "Contact";
                public readonly string Delete = "Delete";
                public readonly string Index = "Index";
                public readonly string Living = "Living";
                public readonly string Sport = "Sport";
                public readonly string WorkEdu = "WorkEdu";
            }
            public readonly string _BasicInfo = "~/Views/Edit/_BasicInfo.cshtml";
            public readonly string _Contact = "~/Views/Edit/_Contact.cshtml";
            public readonly string _Living = "~/Views/Edit/_Living.cshtml";
            public readonly string _Sport = "~/Views/Edit/_Sport.cshtml";
            public readonly string _WorkEdu = "~/Views/Edit/_WorkEdu.cshtml";
            public readonly string BasicInfo = "~/Views/Edit/BasicInfo.cshtml";
            public readonly string Contact = "~/Views/Edit/Contact.cshtml";
            public readonly string Delete = "~/Views/Edit/Delete.cshtml";
            public readonly string Index = "~/Views/Edit/Index.cshtml";
            public readonly string Living = "~/Views/Edit/Living.cshtml";
            public readonly string Sport = "~/Views/Edit/Sport.cshtml";
            public readonly string WorkEdu = "~/Views/Edit/WorkEdu.cshtml";
            static readonly _AboutClass s_About = new _AboutClass();
            public _AboutClass About { get { return s_About; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _AboutClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Edit = "_Edit";
                    public readonly string _Index = "_Index";
                    public readonly string _View = "_View";
                }
                public readonly string _Edit = "~/Views/Edit/About/_Edit.cshtml";
                public readonly string _Index = "~/Views/Edit/About/_Index.cshtml";
                public readonly string _View = "~/Views/Edit/About/_View.cshtml";
            }
            static readonly _AchievementsClass s_Achievements = new _AchievementsClass();
            public _AchievementsClass Achievements { get { return s_Achievements; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _AchievementsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Edit = "_Edit";
                    public readonly string _Index = "_Index";
                    public readonly string _View = "_View";
                }
                public readonly string _Edit = "~/Views/Edit/Achievements/_Edit.cshtml";
                public readonly string _Index = "~/Views/Edit/Achievements/_Index.cshtml";
                public readonly string _View = "~/Views/Edit/Achievements/_View.cshtml";
            }
            static readonly _PictureClass s_Picture = new _PictureClass();
            public _PictureClass Picture { get { return s_Picture; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PictureClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Edit = "_Edit";
                    public readonly string _Index = "_Index";
                    public readonly string _View = "_View";
                }
                public readonly string _Edit = "~/Views/Edit/Picture/_Edit.cshtml";
                public readonly string _Index = "~/Views/Edit/Picture/_Index.cshtml";
                public readonly string _View = "~/Views/Edit/Picture/_View.cshtml";
            }
            static readonly _ProfileClass s_Profile = new _ProfileClass();
            public _ProfileClass Profile { get { return s_Profile; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ProfileClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Edit = "_Edit";
                    public readonly string _Index = "_Index";
                    public readonly string _View = "_View";
                }
                public readonly string _Edit = "~/Views/Edit/Profile/_Edit.cshtml";
                public readonly string _Index = "~/Views/Edit/Profile/_Index.cshtml";
                public readonly string _View = "~/Views/Edit/Profile/_View.cshtml";
            }
            static readonly _ResultsClass s_Results = new _ResultsClass();
            public _ResultsClass Results { get { return s_Results; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ResultsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Edit = "_Edit";
                    public readonly string _Index = "_Index";
                    public readonly string _View = "_View";
                }
                public readonly string _Edit = "~/Views/Edit/Results/_Edit.cshtml";
                public readonly string _Index = "~/Views/Edit/Results/_Index.cshtml";
                public readonly string _View = "~/Views/Edit/Results/_View.cshtml";
            }
            static readonly _ResumeClass s_Resume = new _ResumeClass();
            public _ResumeClass Resume { get { return s_Resume; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ResumeClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Edit = "_Edit";
                    public readonly string _Index = "_Index";
                    public readonly string _View = "_View";
                }
                public readonly string _Edit = "~/Views/Edit/Resume/_Edit.cshtml";
                public readonly string _Index = "~/Views/Edit/Resume/_Index.cshtml";
                public readonly string _View = "~/Views/Edit/Resume/_View.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_EditController : Phoenix.PhoenixApp.Presentation.MVC.Client.Controllers.EditController
    {
        public T4MVC_EditController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult About(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.AboutModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.About);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Achievements(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.AchievementsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Achievements);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BasicInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BasicInfo);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BasicInfo(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.BasicInfoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BasicInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Contact()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contact);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Contact(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.ContactModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteConfirmed(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Living(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.LivingModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Living);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Picture()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Picture);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ProfileSummary(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.ProfileSummaryModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Results(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.ResultsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Results);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Resume(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.ResumeModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Resume);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Sport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Sport);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Sport(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.SportModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Sport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult WorkEdu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WorkEdu);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult WorkEdu(Phoenix.PhoenixApp.Presentation.MVC.Models.ProfileModule.WorkEduModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WorkEdu);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
