// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Phoenix.PhoenixApp.Presentation.MVC.Client.Controllers
{
    public partial class ProfileController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProfileController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Counter()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Counter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Medias()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Medias);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Picture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Picture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Posts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Posts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Stats()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Stats);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Suggest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Suggest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileController Actions { get { return MVCT.Profile; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Profile";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Profile";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Counter = "Counter";
            public readonly string Friends = "Friends";
            public readonly string Index = "Index";
            public readonly string Medias = "Medias";
            public readonly string Picture = "Picture";
            public readonly string Posts = "Posts";
            public readonly string Stats = "Stats";
            public readonly string Suggest = "Suggest";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Counter = "Counter";
            public const string Friends = "Friends";
            public const string Index = "Index";
            public const string Medias = "Medias";
            public const string Picture = "Picture";
            public const string Posts = "Posts";
            public const string Stats = "Stats";
            public const string Suggest = "Suggest";
        }


        static readonly ActionParamsClass_Counter s_params_Counter = new ActionParamsClass_Counter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Counter CounterParams { get { return s_params_Counter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Counter
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Friends s_params_Friends = new ActionParamsClass_Friends();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Friends FriendsParams { get { return s_params_Friends; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Friends
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_Medias s_params_Medias = new ActionParamsClass_Medias();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Medias MediasParams { get { return s_params_Medias; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Medias
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_Picture s_params_Picture = new ActionParamsClass_Picture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Picture PictureParams { get { return s_params_Picture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Picture
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_Posts s_params_Posts = new ActionParamsClass_Posts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Posts PostsParams { get { return s_params_Posts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Posts
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_Stats s_params_Stats = new ActionParamsClass_Stats();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Stats StatsParams { get { return s_params_Stats; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Stats
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_Suggest s_params_Suggest = new ActionParamsClass_Suggest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Suggest SuggestParams { get { return s_params_Suggest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Suggest
        {
            public readonly string username = "username";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Achieve = "_Achieve";
                public readonly string _Contact = "_Contact";
                public readonly string _Counter = "_Counter";
                public readonly string _Dashboard = "_Dashboard";
                public readonly string _Profile = "_Profile";
                public readonly string _ProfileHeader = "_ProfileHeader";
                public readonly string _Results = "_Results";
                public readonly string _Resume = "_Resume";
                public readonly string Index = "Index";
                public readonly string Stats = "Stats";
                public readonly string Suggest = "Suggest";
            }
            public readonly string _Achieve = "~/Views/Profile/_Achieve.cshtml";
            public readonly string _Contact = "~/Views/Profile/_Contact.cshtml";
            public readonly string _Counter = "~/Views/Profile/_Counter.cshtml";
            public readonly string _Dashboard = "~/Views/Profile/_Dashboard.cshtml";
            public readonly string _Profile = "~/Views/Profile/_Profile.cshtml";
            public readonly string _ProfileHeader = "~/Views/Profile/_ProfileHeader.cshtml";
            public readonly string _Results = "~/Views/Profile/_Results.cshtml";
            public readonly string _Resume = "~/Views/Profile/_Resume.cshtml";
            public readonly string Index = "~/Views/Profile/Index.cshtml";
            public readonly string Stats = "~/Views/Profile/Stats.cshtml";
            public readonly string Suggest = "~/Views/Profile/Suggest.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ProfileController : Phoenix.PhoenixApp.Presentation.MVC.Client.Controllers.ProfileController
    {
        public T4MVC_ProfileController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Counter(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Counter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Friends(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Friends);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Friends()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Friends);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Medias(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Medias);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Picture(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Picture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Posts(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Posts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Stats(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Stats);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Suggest(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Suggest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
