// <auto-generated />
namespace Phoenix.PhoenixApp.Infrastructure.Data.MainBoundedContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMedia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMedia));
        
        string IMigrationMetadata.Id
        {
            get { return "201212241131555_AddMedia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
